# Run SQL Queries Here

Simple notebook to help you quickly explore the postgres database.

### Steps:

1. Run the below cell and the helper function will connect to postgres and return the results available tables.
2. Use subsequent notebook cells to explore the database with your own sql queries.
  
  

> NOTE: If prompted to select a kernal in GitHub codespaces, please select `/usr/local/bin/python`

In [1]:
from data_contract_components.data_assets._query_postgres_helper import PostgresDB
import pandas as pd

# setup display to show all columns
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

# setup postgres connection
sql = PostgresDB()
sql.query("SELECT table_name FROM information_schema.tables WHERE table_schema = 'public'")

                   table_name
0             alembic_version
1                      object
2              object_history
3  object_physical_properties
4         object_gallery_info
5                 object_tags
6               object_images
7            object_copyright
8         object_api_metadata

In [3]:
sql_query_str = """
select * from object_images limit 10;
"""
sql.query(sql_query_str)

Empty DataFrame
Columns: [object_id, image, is_primary_image, created_at]
Index: []